# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d283eb8c66c5664313a87cda227da1574973feb7416d696d639bb46283fbcfc60046240d78b3057f1874342d11c76cd97ce969555103d28ae5478f919250eab

test:
  secret_key_base: 52aaad2f873729c935341d40a55f066ff9e5f89326cae5acc0f432bfd4f9c5f6fb19a6bb6ed8c255ef8342f6cffd64b30c9998a921cb7ace9f4e87095e85bb58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
